# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9
  jobs:
    pre_build:
      # just nice to know what's happening up there...
      - env | sort | uniq
      - conda --version && conda list

      # DEPLOY_TARGET is set in our readthedocs admin interface, and should
      # be one of the supported targets: [ primary, arc_iframe ]
      - make ${DEPLOY_TARGET}-stylelinks

      # the above may generate a dirty git cache for some committed symbolic links - ignore. ref:
      # https://docs.readthedocs.io/en/stable/build-customization.html#avoid-having-a-dirty-git-index
      - git update-index --assume-unchanged theme.yml
    post_build:
      - cp docs/googlebb095fa38c4e87cf.html $READTHEDOCS_OUTPUT/html/
      - ls -lR $READTHEDOCS_OUTPUT/html/

conda:
  environment: conda.yaml

mkdocs:
  configuration: mkdocs.yml

submodules:
  include: all
  recursive: true
