#!/bin/csh
#
# Example of OpenMP run using 4 processors on NCAR's bluevista

#BSUB -n 1                              # number of tasks
#BSUB -R "span[hosts=1]"                # max jobs run on one host
#BSUB -J cm1run                         # job name
#BSUB -o cm1run.out                     # ouput filename
#BSUB -e cm1run.err                     # error filename
#BSUB -q share                          # queue
#BSUB -W 1:00                           # wallclock limit (hh:ss)
#BSUB -P 64000040                       # project number

setenv OMP_NUM_THREADS 4

cd /ptmp/gbryan/testit/run/omp4
./cm1.exe >&! cm1.print.out

