#!/bin/csh
#
# Example of single processor run on NCAR's bluevista

#BSUB -n 1                              # number of tasks
#BSUB -J cm1run                         # job name
#BSUB -o cm1run.out                     # ouput filename
#BSUB -e cm1run.err                     # error filename
#BSUB -q share                          # queue
#BSUB -W 1:00                           # wallclock limit (hh:ss)
#BSUB -P 64000040                       # project number

cd /ptmp/gbryan/testit/run/sp
./cm1.exe >&! cm1.print.out

