#!/bin/csh
#
# Example of MPI run using 16 processors (2 nodes) on NCAR's bluevista

#BSUB -a poe                            # use LSF poe elim
#BSUB -x                                # exclusive use of node
#BSUB -n 16                             # total tasks (MPI) needed
#BSUB -R "span[ptile=8]"                # max number of tasks (MPI) per node
#BSUB -J cm1run                         # job name
#BSUB -o cm1run.out                     # ouput filename
#BSUB -e cm1run.err                     # error filename
#BSUB -q premium                        # queue
#BSUB -W 0:10                           # wallclock limit (hh:ss)
#BSUB -P 64000040                       # project number

cd /ptmp/gbryan/testit/run/run16
mpirun.lsf ./cm1.exe >&! cm1.print.out

